name: Deploy to AWS

on:
  push:
    branches:
      - test  

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del repositorio
        uses: actions/checkout@v2

      - name: Login en Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Construir y subir imagen a Docker Hub
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/disminuye_capacity_parkinglot_image:latest .
          docker push ${{ secrets.DOCKER_USERNAME }}/disminuye_capacity_parkinglot_image:latest

      - name: Conectar a AWS EC2 y desplegar
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST_M }}
          username: ${{ secrets.EC2_USER_M }}
          key: ${{ secrets.EC2_SSH_KEY_M }}
          script: |
            echo "🚀 Iniciando despliegue en AWS EC2..."

            # Detener y eliminar el contenedor si ya existe
            if sudo docker ps -a --format '{{.Names}}' | grep -q disminuye_capacity_parkinglot_container; then
              echo "🛑 Deteniendo y eliminando contenedor existente..."
              sudo docker stop disminuye_capacity_parkinglot_container
              sudo docker rm disminuye_capacity_parkinglot_container
            fi

            # Remover imágenes antiguas para evitar acumulación
            echo "🧹 Limpiando imágenes antiguas..."
            sudo docker image prune -af || true

            # Descargar la última versión de la imagen desde Docker Hub
            echo "📥 Descargando nueva imagen..."
            sudo docker pull ${{ secrets.DOCKER_USERNAME }}/disminuye_capacity_parkinglot_image:latest

            # Ejecutar el nuevo contenedor con los valores especificados
            echo "🚀 Ejecutando nuevo contenedor..."
            sudo docker run -d -p 7007:7007 --name disminuye_capacity_parkinglot_container \
              -e PORT=7007 \
              -e DB_HOST=54.225.222.50 \
              -e DB_USER=root \
              -e DB_PASSWORD=admin1234 \
              -e DB_NAME=ParkingLotDB \
              -e PARKINGLOT_SERVICE_URL=http://34.196.247.137:7003/parkinglots \
              -e PARKINGLOT_SERVICE_CAPACITY_URL=http://98.84.148.242:7004/parkinglot/capacity \
              ${{ secrets.DOCKER_USERNAME }}/disminuye_capacity_parkinglot_image:latest

            echo "✅ Despliegue completado con éxito."
